### ISSUE TITLE
HISTORY

### ISSUE THREAD

**Issue by bresu** [bresu/buecherboerse#15]
### History fields

- **Seller** and **Offer** will get history fields. 
- Offer will therefore lose the "createdAt" field

Many issues will arise from this. E.g:
1. What happens with search queries like ?created_before (i will try to keep this syntax, will have to change the underlying logic)
2. Will add new search filters to sort for recently modified offers/ seller

_And many more! Let the fun begin_

**Comment by bresu** [comment]
### TODOS

- [x] remove member_id, createdAt and modifiedAt from offers (history knows this)
- [x] list views do **not** return history, model/<id>/details **does**
- [ ] filters & sorting should still work. -> branch to test performance

Optional: think about adding history to offers (sanity & ease of use?)

**Comment by bresu** [comment]
Offer history implemented in 5862739, testing soon
